#!/usr/bin/ash

run_hook() {
    modprobe -a -q dm-crypt >/dev/null 2>&1

    echo 'dmsetup ls'
    dmsetup ls

    echo 'lsblk -o NAME,FSTYPE,SIZE,FSAVAIL,TYPE,LABEL,MOUNTPOINTS'
    lsblk -o NAME,FSTYPE,SIZE,FSAVAIL,TYPE,LABEL,MOUNTPOINTS

    echo 'fdisk -l'
    fdisk -l

    echo 'decrypt boot'
    #cryptsetup luksOpen /dev/disk/by-uuid/@BootUUID @CryptBootFS --key-file=@BootKey
    cryptsetup -v luksOpen /dev/disk/by-uuid/@BootUUID @CryptBootFS --key-file=@BootKey

    echo 'decrypt root'
    cryptsetup luksOpen /dev/disk/by-uuid/@RootUUID @CryptRootFS --key-file=@RootKey --header @RootHeader

    echo 'decrypted'
}
