#!/usr/bin/ash

run_hook() {
    modprobe -a -q dm-crypt >/dev/null 2>&1

    echo 'sleep 10'
    sleep 10

    echo 'ls'
    ls

    echo 'ls /bin/'
    ls /bin/

    echo 'ls -la /dev/'
    ls -la /dev/
    ls -la /dev/disk/by-id/
    ls -la /dev/disk/by-uuid/
    ls -la /dev/disk/by-partlabel/

    echo 'dmsetup ls'
    dmsetup ls

    echo 'cryptsetup luksClose'
    cryptsetup luksClose /dev/disk/by-uuid/@BootUUID

    echo 'cryptsetup luksClose'
    cryptsetup luksClose @CryptBootFS

    #echo 'decrypt boot'
    #cryptsetup luksOpen /dev/disk/by-uuid/@BootUUID @CryptBootFS --key-file=@BootKey
    echo 'decrypt boot @BootUUID @CryptBootFS @BootKey'
    cryptsetup -v luksOpen /dev/disk/by-uuid/@BootUUID @CryptBootFS --key-file=@BootKey

    echo 'decrypt root'
    cryptsetup luksOpen /dev/disk/by-uuid/@RootUUID @CryptRootFS --key-file=@RootKey --header @RootHeader

    echo 'decrypted'
}
