#!/usr/bin/ash

run_hook() {
    modprobe -a -q dm-crypt >/dev/null 2>&1

    echo 'decrypt boot'
    cryptsetup luksOpen /dev/disk/by-uuid/@BootUUID @CryptBootFS --key-file=@BootKey

    echo 'decrypt root'
    cryptsetup luksOpen /dev/disk/by-uuid/@RootUUID @CryptRootFS --key-file=@RootKey --header @RootHeader

    echo 'decrypted'
}
